markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
title: Alex Warren
author: Alex Warren
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
paginate: 5
collections:
  projects:
    output: true
    permalink: /projects/:title