markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
collections:
  talks:
    output: true
    permalink: /talks/:title
gems:
  - jekyll-feed
  - jekyll-sitemap
title: Alex Warren
author: Alex Warren